<nav class="menu">
		<ul >
		   <li> <a <?php echo ($page=="index_page")?"class='menu'":"";  ?> href="index.php"> Home Page </a> </li>
		   <li> <a <?php echo ($page=="product_page")?"class='menu'":"";  ?> href="product.php"> Product Types </a> </li>
		   <li> <a <?php echo ($page=="enquire_page")?"class='menu'":"";  ?> href="enquire.php"> Product Enquiry </a> </li>
		   <li> <a <?php echo ($page=="payment_page")?"class='menu'":"";  ?> href="payment.php"> Payment </a> </li>
		   <li> <a <?php echo ($page=="about_page")?"class='menu'":"";  ?> href="about.php"> About us </a> </li>
                   <li> <a <?php echo ($page=="manager_page")?"class='menu'":"";  ?> href="enhancements4.php"> Manager </a> </li>
                   <li> <a <?php echo ($page=="latesttrend_page")?"class='menu'":"";  ?> href="enhancements3.php"> Latest Trend </a> </li>
					
		</ul>
</nav> 


